var LIGHT_GRAY = "#E1E1E3";
var DARK_GRAY = "#BFBFC1";
var ROW_COLOR = "#F2F2F3";
var HEADER_COLOR = "#E4E3E8";
var INFO_TITLE_GRAY = "#676767";
var LIST_LINE_GRAY = "#F1F1F3";
var LIST_UNDERLINE_GRAY = "#CFCFCF";
var LIST_HEADER_COLOR = LIGHT_GRAY;

var DICE_YELLOW = "#FFF000";
var DICE_GREEN = "#3CAC3E";
var DICE_PURPLE = "#E4E3E8";
var DICE_BLUE = "#6CCDDF";
var DICE_PURPLE = "#461F78";
var DICE_RED = "#E6001E";

var HEADER_HEIGHT = 20;
var LIST_HEADER_HEIGHT = 22;
var OBLIGATION_HEIGHT = 100;
var CHARACTER_HEIGHT = 150

var STATUS_BAR_HEIGHT = 20;
var SCREEN_WIDTH = 1024;
var SCREEN_HEIGHT = 768;
